<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"  />
    <PackageReference Include="Verify.Xunit" />
    <PackageReference Include="xunit"  />
    <PackageReference Include="xunit.runner.visualstudio"  />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KristofferStrube.ActivityPubBotDotNet.Server\KristofferStrube.ActivityPubBotDotNet.Server.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="UnitTest1.FollowHandler_Follow.verified.txt">
      <DependentUpon>FollowHandler.cs</DependentUpon>
    </None>
  </ItemGroup>
</Project>